# Step 1: Base image
FROM node:20-bookworm

# Step 2: Set the working directory inside the container
WORKDIR  /app

# Copy the package.json and package-lock.json files to the /build directory
COPY package*.json ./

# RUN npm config set strict-ssl false -g

# Set NODE_TLS_REJECT_UNAUTHORIZED to 0
# ENV NODE_TLS_REJECT_UNAUTHORIZED=0

# RUN npm install -g npm 
ENV NODE_TLS_REJECT_UNAUTHORIZED=0 
RUN npm config set strict-ssl false

RUN npm install -g npm@latest
RUN npm cache clean -f
RUN npm install --cpu=x64 --os=linux --libc=glibc sharp
# RUN npm install --include=optional sharp
# Install production dependencies and clean the cache
# RUN npm install express 
# RUN npm install 


# Step 5: Copy the rest of the application files (excluding those in .dockerignore)
COPY . .


# Step 6: Expose the port your app will run on
EXPOSE 8080


# Step 8: Command to start the app
CMD ["npm", "start"]
