// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7SU5g9b10FOA7WLzL253Pl4HLtghpOls',
    appId: '1:239260696903:web:cddf4e680028e0a1ce4c62',
    messagingSenderId: '239260696903',
    projectId: 'remsenseai',
    authDomain: 'remsenseai.firebaseapp.com',
    storageBucket: 'remsenseai.appspot.com',
    measurementId: 'G-6YLS922L9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8WheWsUCh6_aao43Qk5LHNwd6EDnAimk',
    appId: '1:239260696903:android:8e13d37168b99315ce4c62',
    messagingSenderId: '239260696903',
    projectId: 'remsenseai',
    storageBucket: 'remsenseai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfVbbx295MaTB51LQBoYP9pp08N_c8Hlo',
    appId: '1:239260696903:ios:1638749b7f6044cdce4c62',
    messagingSenderId: '239260696903',
    projectId: 'remsenseai',
    storageBucket: 'remsenseai.appspot.com',
    iosBundleId: 'com.example.remoteSensing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfVbbx295MaTB51LQBoYP9pp08N_c8Hlo',
    appId: '1:239260696903:ios:1638749b7f6044cdce4c62',
    messagingSenderId: '239260696903',
    projectId: 'remsenseai',
    storageBucket: 'remsenseai.appspot.com',
    iosBundleId: 'com.example.remoteSensing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7SU5g9b10FOA7WLzL253Pl4HLtghpOls',
    appId: '1:239260696903:web:2d4d0414023fc2f4ce4c62',
    messagingSenderId: '239260696903',
    projectId: 'remsenseai',
    authDomain: 'remsenseai.firebaseapp.com',
    storageBucket: 'remsenseai.appspot.com',
    measurementId: 'G-6M3LC3FZHT',
  );
}
